-- MySQL Script generated by MySQL Workbench
-- Fri Dec  3 12:31:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TTS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TTS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TTS` DEFAULT CHARACTER SET utf8 ;
USE `TTS` ;

-- -----------------------------------------------------
-- Table `TTS`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TTS`.`Users` (
                                              `idUsers` INT NOT NULL AUTO_INCREMENT,
                                              `firstName` VARCHAR(45) NOT NULL,
    `secondName` VARCHAR(45) NOT NULL,
    `login` VARCHAR(45) NOT NULL,
    `password` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`idUsers`),
    UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TTS`.`App`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TTS`.`App` (
                                            `idApp` INT NOT NULL AUTO_INCREMENT,
                                            `nameApp` VARCHAR(45) NOT NULL,
    `Users_idUsers` INT NOT NULL,
    `linkToIcon` VARCHAR(128) NULL,
    PRIMARY KEY (`idApp`, `Users_idUsers`),
    INDEX `fk_App_Users_idx` (`Users_idUsers` ASC) VISIBLE,
    CONSTRAINT `fk_App_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `TTS`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TTS`.`LifeCycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TTS`.`LifeCycle` (
                                                  `idLifeCycle` INT NOT NULL AUTO_INCREMENT,
                                                  `startApp` DATETIME(1) NULL,
    `closeApp` DATETIME(1) NULL,
    `App_idApp` INT NOT NULL,
    `App_Users_idUsers` INT NOT NULL,
    PRIMARY KEY (`idLifeCycle`, `App_idApp`, `App_Users_idUsers`),
    INDEX `fk_LifeCycle_App1_idx` (`App_idApp` ASC, `App_Users_idUsers` ASC) VISIBLE,
    CONSTRAINT `fk_LifeCycle_App1`
    FOREIGN KEY (`App_idApp` , `App_Users_idUsers`)
    REFERENCES `TTS`.`App` (`idApp` , `Users_idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TTS`.`Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TTS`.`Activity` (
                                                 `idActivity` INT NOT NULL AUTO_INCREMENT,
                                                 `startOfUse` DATETIME(1) NULL,
    `endOfUse` DATETIME(1) NULL,
    `LifeCycle_idLifeCycle` INT NOT NULL,
    `LifeCycle_App_idApp` INT NOT NULL,
    `LifeCycle_App_Users_idUsers` INT NOT NULL,
    PRIMARY KEY (`idActivity`, `LifeCycle_idLifeCycle`, `LifeCycle_App_idApp`, `LifeCycle_App_Users_idUsers`),
    INDEX `fk_Activity_LifeCycle1_idx` (`LifeCycle_idLifeCycle` ASC, `LifeCycle_App_idApp` ASC, `LifeCycle_App_Users_idUsers` ASC) VISIBLE,
    CONSTRAINT `fk_Activity_LifeCycle1`
    FOREIGN KEY (`LifeCycle_idLifeCycle` , `LifeCycle_App_idApp` , `LifeCycle_App_Users_idUsers`)
    REFERENCES `TTS`.`LifeCycle` (`idLifeCycle` , `App_idApp` , `App_Users_idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
